import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore - allow importing global CSS without a dedicated type declaration
import "./globals.css";
import NavBarNew from "@/components/widgets/NavBarNew";
import BackgroundGrid from "@/components/BackgroundGrid";
import Heighlighter from "@/components/widgets/Heighlighter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const containerHeight = 3200; // Taller for home page
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-screen relative overflow-auto`}
        style={{
          backgroundColor: "#f0f0f0",
          backgroundImage: `
            linear-gradient(to right, #e5e7eb 1px, transparent 1px),
            linear-gradient(to bottom, #e5e7eb 1px, transparent 1px)
          `,
          backgroundSize: "20px 20px",
        }}
      >
        <BackgroundGrid>
          <NavBarNew />
          {children}
          <Heighlighter />
        </BackgroundGrid>
      </body>
    </html>
  );
}
